<?php

namespace gbprojet\MainBundle\Entity;

/**
 * batimentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class batimentRepository extends \Doctrine\ORM\EntityRepository
{
}
