<?php

namespace gbprojet\MainBundle\Entity;

/**
 * DepartementSpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartementSpRepository extends \Doctrine\ORM\EntityRepository
{
}
