<?php

namespace gbprojet\MainBundle\Entity;

/**
 * DepartementEcueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartementEcueRepository extends \Doctrine\ORM\EntityRepository
{
}
