<?php

namespace gbprojet\MainBundle\Entity;

/**
 * ecueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ecueRepository extends \Doctrine\ORM\EntityRepository
{
}
