<?php

namespace gbprojet\MainBundle\Entity;

/**
 * enseignantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class enseignantRepository extends \Doctrine\ORM\EntityRepository
{
}
