<?php

namespace gbprojet\MainBundle\Entity;

/**
 * salleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class salleRepository extends \Doctrine\ORM\EntityRepository
{
}
