<?php

namespace gbprojet\MainBundle\Entity;

/**
 * seanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class seanceRepository extends \Doctrine\ORM\EntityRepository
{
}
