<?php

namespace gbprojet\MainBundle\Entity;

/**
 * spRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class spRepository extends \Doctrine\ORM\EntityRepository
{
}
