<?php

namespace gbprojet\MainBundle\Entity;

/**
 * titreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class titreRepository extends \Doctrine\ORM\EntityRepository
{
}
