<?php

namespace gbprojet\MainBundle\Entity;

/**
 * typeseanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typeseanceRepository extends \Doctrine\ORM\EntityRepository
{
}
