<?php

namespace gbprojet\MainBundle\Entity;

/**
 * typesalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typesalleRepository extends \Doctrine\ORM\EntityRepository
{
}
