<?php

namespace gbprojet\MainBundle\Entity;

/**
 * ufrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ufrRepository extends \Doctrine\ORM\EntityRepository
{
}
